<a href="https://colab.research.google.com/github/akritivishwakarma2007/DE-journey/blob/main/Pivot_Table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pivot Table

The pivot table takes simple column-wise data as input, and groups the entries into a two-dimensional table that provides a multidimensional summarization of the data.

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.groupby('sex')['total_bill'].mean()

/tmp/ipykernel_8455/3379495421.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')['total_bill'].mean()

sex
Male      20.744076
Female    18.056897
Name: total_bill, dtype: float64

In [ ]:
df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

/tmp/ipykernel_8455/884363850.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill')

/tmp/ipykernel_8455/4282385320.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
# aggfunc
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='mean')

/tmp/ipykernel_8455/1751944094.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='mean')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='max')
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='min')
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='count')
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='median')
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='sum')

/tmp/ipykernel_8455/3903295305.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='max')
/tmp/ipykernel_8455/3903295305.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='min')
/tmp/ipykernel_8455/3903295305.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='count')
/tmp/ipykernel_8455/3903295305.py:4: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='median')
/tmp/ipykernel_8455/3903295305.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='sum')

smoker      Yes       No
sex
Male    1337.07  1919.75
Female   593.27   977.68

In [ ]:
# all cols together
df.pivot_table(index='sex',columns='smoker')['size']

/tmp/ipykernel_8455/3226264718.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker')['size']

TypeError: category dtype does not support aggregation 'mean'

In [ ]:
# all cols together
df.pivot_table(index='sex',columns='smoker', values='size')

/tmp/ipykernel_8455/1002198549.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker', values='size')

smoker       Yes        No
sex
Male    2.500000  2.711340
Female  2.242424  2.592593

In [28]:
df.pivot_table(index=['sex','smoker'],columns=['day','time'])

/tmp/ipykernel_8455/1883326029.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index=['sex','smoker'],columns=['day','time'])

                   size                                                   tip  \
day                Thur              Fri              Sat       Sun      Thur
time              Lunch Dinner     Lunch Dinner    Dinner    Dinner     Lunch
sex    smoker
Male   Yes     2.300000    NaN  1.666667    2.4  2.629630  2.600000  3.058000
       No      2.500000    NaN       NaN    2.0  2.656250  2.883721  2.941500
Female Yes     2.428571    NaN  2.000000    2.0  2.200000  2.500000  2.990000
       No      2.500000    2.0  3.000000    2.0  2.307692  3.071429  2.437083

                                                      total_bill         \
day                    Fri              Sat       Sun       Thur
time          Dinner Lunch Dinner    Dinner    Dinner      Lunch Dinner
sex    smoker
Male   Yes       NaN  1.90  3.246  2.879259  3.521333  19.171000    NaN
       No        NaN   NaN  2.500  3.256563  3.115349  18.486500    NaN
Female Yes       NaN  2.66  2.700  2.868667  3.500000  19.218571    NaN
       No        3.0  3.00  3.250  2.724615  3.329286  15.899167  18.78


day                  Fri                Sat        Sun
time               Lunch  Dinner     Dinner     Dinner
sex    smoker
Male   Yes     11.386667  25.892  21.837778  26.141333
       No            NaN  17.475  19.929063  20.403256
Female Yes     13.260000  12.200  20.266667  16.540000
       No      15.980000  22.750  19.003846  20.824286

In [29]:
df.pivot_table(index=['sex','smoker'],columns=['day','time'],aggfunc={'size':'mean','tip':'max','total_bill':'sum'})

/tmp/ipykernel_8455/1197169075.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index=['sex','smoker'],columns=['day','time'],aggfunc={'size':'mean','tip':'max','total_bill':'sum'})

                   size                                               tip  \
day                Thur              Fri              Sat       Sun  Thur
time              Lunch Dinner     Lunch Dinner    Dinner    Dinner Lunch
sex    smoker
Male   Yes     2.300000    NaN  1.666667    2.4  2.629630  2.600000  5.00
       No      2.500000    NaN       NaN    2.0  2.656250  2.883721  6.70
Female Yes     2.428571    NaN  2.000000    2.0  2.200000  2.500000  5.00
       No      2.500000    2.0  3.000000    2.0  2.307692  3.071429  5.17

                                                total_bill                \
day                    Fri           Sat    Sun       Thur           Fri
time          Dinner Lunch Dinner Dinner Dinner      Lunch Dinner  Lunch
sex    smoker
Male   Yes       NaN  2.20   4.73  10.00    6.5     191.71   0.00  34.16
       No        NaN   NaN   3.50   9.00    6.0     369.73   0.00   0.00
Female Yes       NaN  3.48   4.30   6.50    4.0     134.53   0.00  39.78
       No        3.0  3.00   3.25   4.67    5.2     381.58  18.78  15.98


day                     Sat           Sun
time           Dinner Lunch  Dinner Lunch  Dinner
sex    smoker
Male   Yes     129.46   0.0  589.62   0.0  392.12
       No       34.95   0.0  637.73   0.0  877.34
Female Yes      48.80   0.0  304.00   0.0   66.16
       No       22.75   0.0  247.05   0.0  291.54